### ISSUE TITLE
Can't move when starting game

### ISSUE THREAD

**Issue by LimeSkillZ** [NotestQ/PerformanceSettings#3]
Creating a game freezes the character in place and doesn't let you move the camera around.

I'm only using three mods, PerformanceSettings, ContentSettings, and BepInExPack.

**Comment by NotestQ** [comment]
Does this issue persist as of v0.4.3? I released a patch for it an hour or so ago

**Comment by NotestQ** [comment]
From other sources it seems to be solved, will reopen if the issue props up again.
